Add option to ConfigParser to support inline-comments
When using the gpis_settings.ini in its current form I was getting these error when running gpio_control.py. 
```
File "/usr/lib/python3.7/configparser.py", line 802, in _get
    return conv(self.get(section, option, **kwargs))
ValueError: could not convert string to float: '0.1 ; only for rotary encoder'
```
I read a little about the topic and it seems that configparser does not support inline comments in its default state. Therefore the config argument was added.
Works on my machine, but not extensively tested beyond that.